#!groovy
node {
def webPath_dev = '/home/ecosmob/docker/fs_curl/'
def dockerRegistry='dockerregistry.ecosmob.net:5000'

          stage ('Checkout'){
                   checkout scm
                   
                         
        GIT_COMMIT_EMAIL = sh (
        script: 'git --no-pager show -s --format=\'%ae\'',
        returnStdout: true
        ).trim()
    
        GIT_COMMIT_ID = sh (
        script: 'git --no-pager show -s | grep commit',
        returnStdout: true
        ).trim()

                   
          }
            
        
          stage('SonarQube analysis') {
                    // requires SonarQube Scanner 2.8+ test1
                    def scannerHome = tool 'Sonar-Scanner';
                    withSonarQubeEnv('SonarQube') {
                    def projectKey1=env.JOB_NAME.replaceAll('/','.')
                    def projectKey=projectKey1.replaceAll('%2','.')
                    sh "${scannerHome}/bin/sonar-scanner -D sonar.projectKey=${projectKey}  -D sonar.sources=. -D sonar.exclusions=config/**,/docker/**,docs/**,mail/**,messages/**,runtime/**,tests/**,vagrant/**,vendor/**,widgets/**,web/**"
                    stash includes: ".scannerwork/report-task.txt", name: 'sonar'
                    }
          }
          
          
          /*stage("Quality Gate"){
                    unstash 'sonar'
                    def props = getProperties(".scannerwork/report-task.txt")
                    def sonarServerUrl=props.getProperty('serverUrl')
                    def ceTaskUrl= props.getProperty('ceTaskUrl')
                    def ceTask
                    def analysisStatus
                    while(analysisStatus != 'SUCCESS') {
                        sleep(5)
                        ceTask = jsonParse(new URL(ceTaskUrl).getText(requestProperties: [Authorization: "Basic " + "admin:admin".getBytes().encodeBase64().toString()]))
                        analysisStatus = ceTask["task"]["status"]
                    }
                    def analysisId = ceTask["task"]["analysisId"]
                    def analysisResultUrl = sonarServerUrl + "/api/qualitygates/project_status?analysisId=" + analysisId
                    def qualitygate = jsonParse(analysisResultUrl.toURL().getText(requestProperties: [Authorization: "Basic " + "admin:admin".getBytes().encodeBase64().toString()]))
                    def qualitygateStatus = qualitygate["projectStatus"]["status"]
                    echo "qualitygateStatus=${qualitygateStatus}"
                    if ("ERROR".equals(qualitygateStatus)) {
                        error "Quality Gate failure"
                    }
            } */


if (env.BRANCH_NAME == 'master')
{ 

 withCredentials( [usernamePassword( credentialsId: 'ecouctcl', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')])
{
  def remote = [:]
  remote.name = 'ecouctcl'
  remote.host = "95.216.154.52"
  remote.port = 52222
  remote.user = "${USERNAME}"
  remote.password = "${PASSWORD}"
  remote.allowAnyHosts = true
        

    stage ('Build and Push the Image')
    {
      withDockerRegistry(credentialsId: 'dockerregistry', url: 'https://dockerregistry.ecosmob.net:5000') {
      def image1 = docker.build("${dockerRegistry}/ecouc-tcl-fscurl:v${env.BUILD_ID}", "--file docker/Dockerfile .")
      image1.push()
    }
    }  
    stage ('Moving the docker-compose to the server to Dev')
    {
    sshPut remote: remote, from: './docker/docker-compose.yml', into: "${webPath_dev}docker-compose.yml"
    }
    
    stage('Start the docker-compose Dev Server') 
    {
      previous = sshCommand remote: remote, command: "cat ${webPath_dev}docker-compose.yml | grep -o ':v.*' | sed 's/://g' ", returnStdout: true
      sshCommand remote: remote, command: "sed -i 's/${previous}/v${env.BUILD_ID}/g' ${webPath_dev}docker-compose.yml"
      sshCommand remote: remote, command: "docker-compose -f ${webPath_dev}docker-compose.yml up -d ; docker ps"
     }  
   }
   
    }
    // If master statement close
    
    if (env.BRANCH_NAME == 'develop')
{ 

 stage ('Build and Push the Image')
    {
      withDockerRegistry(credentialsId: 'dockerregistry', url: 'https://dockerregistry.ecosmob.net:5000') {
      def image1 = docker.build("${dockerRegistry}/ecouc-develop-fscurl:v${env.BUILD_ID}", "--file docker/Dockerfile .")
      image1.push()
    }
    }
      }
    // If develop statement close

    }    // Node close

def Properties getProperties(filename) {
def properties = new Properties()
properties.load(new StringReader(readFile(filename)))
return properties
}

@NonCPS
def jsonParse(def json) {
    new groovy.json.JsonSlurperClassic().parseText(json)
}
